name: svnR-4.0.x
channels:
  - conda-forge
  - nodefaults
dependencies:
  - binutils_linux-64=2.31.1
  - boost
  - bzip2
  - cairo
  - curl
  - fftw
  - fontconfig
  - freetype
  - fribidi
  - gcc_linux-64=7.3.0
  - gfortran_linux-64=7.3.0
  - glib
  - gmp
  - graphite2
  - gsl
  - gxx_linux-64=7.3.0
  - harfbuzz
  - hdf5
  - icu
  - jpeg
  - krb5
  - libcurl
  - libedit
  - libffi
  - libiconv
  - libnetcdf
  - libpng
  - libssh2
  - libtiff
  - libuuid
  - libxcb
  - libxml2
  - make
  - mpc
  - mpfr
  - ncurses
  - openjpeg
  - pandoc
  - pango
  - pcre
  - pcre2
  - pigz
  - pixman
  - pkg-config
  - poppler
  - readline
  - sqlite
  - texinfo
  - tk
  - tktable
  - udunits2
  - xz
  - zlib
  - zstd

