name: svnR-4.1
channels:
  - conda-forge
  - nodefaults
dependencies:
  - binutils_linux-64=2.31.1
  - boost
  - bzip2
  - cairo
  - curl
  - fftw
  - fontconfig
  - freetype
  - fribidi
  - gcc_linux-64=7.3.0
  - gdal
  - gfortran_linux-64=7.3.0
  - glib
  - gmp
  - graphite2
  - gsl
  - gxx_linux-64=7.3.0
  - harfbuzz
  - hdf5
  - icu
  - imagemagick
  - jags
  - jpeg
  - krb5
  - libcurl
  - libedit
  - libffi
  - libgdal
  - libgit2
  - libgomp
  - libiconv
  - libnetcdf
  - libpng
  - libssh2
  - libtiff
  - libuuid
  - libv8
  - libxcb
  - libxml2
  - make
  - mpc
  - mpfr
  - ncurses
  - openblas
  - openjdk
  - openjpeg
  - pandoc
  - pango
  - pcre
  - pcre2
  - pigz
  - pixman
  - pkg-config
  - poppler
  - readline
  - sqlite
  - texinfo
  - tk
  - tktable
  - udunits2
  - xorg-kbproto
  - xorg-libice
  - xorg-libsm
  - xorg-libx11
  - xorg-libxau
  - xorg-libxext
  - xorg-libxrender
  - xorg-libxt
  - xorg-renderproto
  - xorg-xextproto
  - xorg-xproto
  - xz
  - zlib
  - zstd

